System check identified some issues:

WARNINGS:
Main.Item.pubdate: (fields.W161) Fixed default value provided.
	HINT: It seems you set a fixed date / time / datetime value as default for this field. This may not be what you want. If you want to have the current date as default, use `django.utils.timezone.now`
/usr/local/lib/python3.5/dist-packages/django/db/models/fields/__init__.py:1430: RuntimeWarning: DateTimeField Item.pubdate received a naive datetime (2016-12-10 17:34:13) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.5/dist-packages/django/db/models/fields/__init__.py:1430: RuntimeWarning: DateTimeField Item.pubdate received a naive datetime (2016-12-10 16:38:21) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.5/dist-packages/django/db/models/fields/__init__.py:1430: RuntimeWarning: DateTimeField Item.pubdate received a naive datetime (2016-12-10 16:03:58) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.5/dist-packages/django/db/models/fields/__init__.py:1430: RuntimeWarning: DateTimeField Item.pubdate received a naive datetime (2016-12-10 15:50:50) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.5/dist-packages/django/db/models/fields/__init__.py:1430: RuntimeWarning: DateTimeField Item.pubdate received a naive datetime (2016-12-10 13:33:11) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.5/dist-packages/django/db/models/fields/__init__.py:1430: RuntimeWarning: DateTimeField Item.pubdate received a naive datetime (2016-12-10 12:47:05) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.5/dist-packages/django/db/models/fields/__init__.py:1430: RuntimeWarning: DateTimeField Item.pubdate received a naive datetime (2016-12-10 11:21:36) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.5/dist-packages/django/db/models/fields/__init__.py:1430: RuntimeWarning: DateTimeField Item.pubdate received a naive datetime (2016-12-10 10:49:45) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.5/dist-packages/django/db/models/fields/__init__.py:1430: RuntimeWarning: DateTimeField Item.pubdate received a naive datetime (2016-12-09 23:42:47) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.5/dist-packages/django/db/models/fields/__init__.py:1430: RuntimeWarning: DateTimeField Item.pubdate received a naive datetime (2016-12-09 18:14:12) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.5/dist-packages/django/db/models/fields/__init__.py:1430: RuntimeWarning: DateTimeField Item.pubdate received a naive datetime (2016-12-09 17:54:36) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.5/dist-packages/django/db/models/fields/__init__.py:1430: RuntimeWarning: DateTimeField Item.pubdate received a naive datetime (2016-12-09 17:50:59) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.5/dist-packages/django/db/models/fields/__init__.py:1430: RuntimeWarning: DateTimeField Item.pubdate received a naive datetime (2016-12-09 17:31:19) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.5/dist-packages/django/db/models/fields/__init__.py:1430: RuntimeWarning: DateTimeField Item.pubdate received a naive datetime (2016-12-09 17:28:30) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.5/dist-packages/django/db/models/fields/__init__.py:1430: RuntimeWarning: DateTimeField Item.pubdate received a naive datetime (2016-12-09 17:09:49) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.5/dist-packages/django/db/models/fields/__init__.py:1430: RuntimeWarning: DateTimeField Item.pubdate received a naive datetime (2016-12-09 17:07:09) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.5/dist-packages/django/db/models/fields/__init__.py:1430: RuntimeWarning: DateTimeField Item.pubdate received a naive datetime (2016-12-09 17:04:40) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.5/dist-packages/django/db/models/fields/__init__.py:1430: RuntimeWarning: DateTimeField Item.pubdate received a naive datetime (2016-12-09 17:00:21) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.5/dist-packages/django/db/models/fields/__init__.py:1430: RuntimeWarning: DateTimeField Item.pubdate received a naive datetime (2016-12-09 16:57:55) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.5/dist-packages/django/db/models/fields/__init__.py:1430: RuntimeWarning: DateTimeField Item.pubdate received a naive datetime (2016-12-09 16:57:07) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.5/dist-packages/django/db/models/fields/__init__.py:1430: RuntimeWarning: DateTimeField Item.pubdate received a naive datetime (2016-12-09 16:54:14) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.5/dist-packages/django/db/models/fields/__init__.py:1430: RuntimeWarning: DateTimeField Item.pubdate received a naive datetime (2016-12-09 16:54:10) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.5/dist-packages/django/db/models/fields/__init__.py:1430: RuntimeWarning: DateTimeField Item.pubdate received a naive datetime (2016-12-09 16:49:30) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.5/dist-packages/django/db/models/fields/__init__.py:1430: RuntimeWarning: DateTimeField Item.pubdate received a naive datetime (2016-12-09 16:47:29) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.5/dist-packages/django/db/models/fields/__init__.py:1430: RuntimeWarning: DateTimeField Item.pubdate received a naive datetime (2016-12-09 16:47:24) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.5/dist-packages/django/db/models/fields/__init__.py:1430: RuntimeWarning: DateTimeField Item.pubdate received a naive datetime (2016-12-09 16:45:57) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.5/dist-packages/django/db/models/fields/__init__.py:1430: RuntimeWarning: DateTimeField Item.pubdate received a naive datetime (2016-12-09 16:45:28) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.5/dist-packages/django/db/models/fields/__init__.py:1430: RuntimeWarning: DateTimeField Item.pubdate received a naive datetime (2016-12-09 16:39:32) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.5/dist-packages/django/db/models/fields/__init__.py:1430: RuntimeWarning: DateTimeField Item.pubdate received a naive datetime (2016-12-09 16:33:39) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.5/dist-packages/django/db/models/fields/__init__.py:1430: RuntimeWarning: DateTimeField Item.pubdate received a naive datetime (2016-12-09 16:21:28) while time zone support is active.
  RuntimeWarning)
Crawling Channel 哈工大综合信息服务网置顶信息
Find Item Nevada Las Vegas 大学朱强教授讲学通知
Find Item 【社区建设】A04公寓社区委员会成功举行防火安全宣传活动
Find Item 【放飞梦想&#8226;激扬青春】化工与化学学院2015级支部大舞台成功举办
Find Item “助力金秀・圆梦中国”项目推进座谈会顺利举行
Find Item 学工办集体学习习总书记在全国高校思想政治工作会议上的讲话
Find Item 航天学院学工办学习全国高校思想政治工作会议精神
Crawling Channel 南都周刊
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/sqlite3/base.py", line 337, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: Main_item.pubdate

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/fu/Code/PycharmProjects/UglyToy/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/home/fu/Code/PycharmProjects/UglyToy/Main/management/commands/crawlperday.py", line 33, in handle
    item.save()
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/base.py", line 796, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/base.py", line 824, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/base.py", line 908, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/base.py", line 947, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 1045, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/sql/compiler.py", line 1054, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.5/dist-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/sqlite3/base.py", line 337, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: Main_item.pubdate
